version: '3.1'

services:

  api:
    command: sh -c "npm install && npm run dev" 
    container_name: api
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://mongo:27017
    image: node:latest
    links: 
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - ${PORT}:${PORT}
    restart: always
    working_dir: /usr/src/api
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules/
    
  mongo:
    container_name: mongo
    env_file:
      - .env
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./seed.js:/docker-entrypoint-initdb.d/mongo-init.js:ro